{{- if .Values.component.master }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
  namespace: {{ $namespace }}
spec:
  ports:
    - port: {{ .Values.master.port }}
      protocol: TCP
      targetPort: {{ .Values.master.port }}
  selector:
{{ tuple $envAll $namespace "master" | include "helm-toolkit.metadata_labels" | indent 4 }}
{{ end }}