{{- if .Values.component.csi }}
{{- $envAll := . }}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cfs-csi-controller
spec:
  selector:
    matchLabels:
      app: cfs-csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cfs-csi-controller
    spec:
      serviceAccount: cfs-csi-service-account
      serviceAccountName: cfs-csi-service-account
      priorityClassName: cubefs-high-priority
    {{- with .Values.csi.controller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- with .Values.csi.controller.tolerations }}
        tolerations:
      {{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: csi-provisioner
          image: {{ $.Values.image.csi_provisioner }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          securityContext:
            privileged: true
          args:
            - --csi-address=$(ADDRESS)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: DRIVER_NAME
              value: {{ $.Values.csi.driverName }}
            - name: ADDRESS
              value: /csi/csi-controller.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: external-attacher
          image: {{ $.Values.image.csi_attacher }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          securityContext:
            privileged: true
          args:
            - --csi-address=$(ADDRESS)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi-controller.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-resizer
          image: {{ $.Values.image.csi_resizer }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          securityContext:
            privileged: true
          args:
            - --csi-address=$(ADDRESS)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi-controller.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: cfs-driver
          image: {{ $.Values.image.csi_driver }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - bash
            - "-c"
            - |-
              set -e
              su -p -s /bin/bash -c "/cfs/bin/start.sh &"
              su -p -s /bin/bash -c "sleep 9999999d"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi-controller.sock
            - name: DRIVER_NAME
              value: {{ $.Values.csi.driverName }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "rm -rf /csi/csi-controller.sock"
                ]
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - hostPath:
            path: {{ $.Values.csi.kubeletPath -}}/plugins/csi.cubefs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: {{ $.Values.csi.kubeletPath -}}/pods
            type: Directory
          name: mountpoint-dir
---
{{ end }}
