{{- if .Values.component.csi }}
{{- $envAll := . }}

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cfs-csi-node
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: cfs-csi-node
  template:
    metadata:
      labels:
        app: cfs-csi-node
    spec:
      serviceAccount: cfs-csi-service-account
      serviceAccountName: cfs-csi-service-account
    {{- with .Values.csi.node.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- with .Values.csi.node.tolerations }}
        tolerations:
      {{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: csi-node-driver-registrar
          image: {{ $.Values.image.driver_registrar }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          securityContext:
            privileged: true
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ $.Values.csi.kubeletPath -}}/plugins/{{- $.Values.csi.driverName -}}/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - name: cfs-driver
          image: {{ $.Values.image.csi_driver }}
          imagePullPolicy: {{ $.Values.image.pull_policy }}
          securityContext:
            privileged: true
          args:
            - bash
            - "-c"
            - |-
              set -e
              su -p -s /bin/bash -c "/cfs/bin/start.sh &"
              su -p -s /bin/bash -c "sleep 9999999d"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DRIVER_NAME
              value: {{ $.Values.csi.driverName }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "rm -rf /csi/csi.sock"
                ]
{{ tuple $envAll $envAll.Values.csi.node.resources | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: {{ $.Values.csi.kubeletPath }}/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - hostPath:
            path: {{ $.Values.csi.kubeletPath -}}/plugins/{{- $.Values.csi.driverName }}
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: {{ $.Values.csi.kubeletPath -}}/plugins_registry
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: {{ $.Values.csi.kubeletPath -}}/pods
            type: Directory
          name: mountpoint-dir
---
{{ end }}
