{{- if .Values.component.blobstore_scheduler }}
{{- $envAll := . }}

---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  ports:
  - port: {{ $.Values.blobstore_scheduler.port }}
    protocol: TCP
    targetPort: {{ $.Values.blobstore_scheduler.port }}
    name: port1
  selector:
    app.kubernetes.io/component: blobstore-scheduler
    app.kubernetes.io/name: cubefs
{{ end }}