{{- if .Values.component.csi }}
{{- $envAll := . }}

{{- $consulAddress := tuple $envAll | include "cubefs.monitor.consul.address" }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc

{{- if .Values.csi.storageClass.setToDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ $.Values.csi.driverName }}
allowVolumeExpansion: true
reclaimPolicy: {{ $.Values.csi.storageClass.reclaimPolicy}}
parameters:
  # Resource manager IP address or URL
  masterAddr: {{ default (include "cubefs.master-service.with.port" .) $.Values.csi.storageClass.masterAddr | quote }}
  # Consul Service IP address or URL
  consulAddr: {{ $consulAddress | quote }}
  # Log level：debug, info, warn, error 
  logLevel: {{ $.Values.csi.logLevel }}
  {{- with .Values.csi.storageClass.otherParameters }}
{{ toYaml . | indent 2 }}
  {{ end }}
---
{{ end }}



