kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "chubaofs-helm.master.fullname" . }}
  labels:
    app: {{ include "chubaofs-helm.name" . }}
    chart: {{ include "chubaofs-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  master-json.sh: |
    #!/bin/sh

    CBFS_CLUSTER_NAME=${CBFS_CLUSTER_NAME:="mycluster"}
    ORDINAL_ID=${HOSTNAME##*-}
    CBFS_ID=$((ORDINAL_ID+1))
    CBFS_PORT=${CBFS_PORT:="17010"}
    CBFS_IP=${CBFS_IP:="127.0.0.1"}
    CBFS_PROF=${CBFS_PROF:="17020"}
    CBFS_PEERS=${CBFS_PEERS:=""}
    CBFS_RETAIN_LOGS=${CBFS_RETAIN_LOGS:="2"}
    CBFS_LOGDIR=${CBFS_LOGDIR:="/cfs/log"}
    CBFS_LOG_LEVEL=${CBFS_LOG_LEVEL:="info"}
    CBFS_WAL_DIR=${CBFS_WAL_DIR:="/cfs/data/wal"}
    CBFS_WARN_LOG_DIR=${CBFS_WARN_LOG_DIR:="/cfs/log"}
    CBFS_STORE_DIR=${CBFS_STORE_DIR:="/cfs/data/store"}
    jq -n \
        --arg clusterName "$CBFS_CLUSTER_NAME" \
        --arg id "$CBFS_ID" \
        --arg role "$CBFS_ROLE" \
        --arg ip "$CBFS_IP" \
        --arg port "$CBFS_PORT" \
        --arg prof "$CBFS_PROF" \
        --arg peers "$CBFS_PEERS" \
        --arg retainLogs "$CBFS_RETAIN_LOGS" \
        --arg logDir "$CBFS_LOGDIR" \
        --arg logLevel "$CBFS_LOG_LEVEL" \
        --arg walDir "$CBFS_WAL_DIR" \
        --arg warnLogDir "$CBFS_WARN_LOG_DIR" \
        --arg storeDir "$CBFS_STORE_DIR" \
          '{
            "clusterName": $clusterName,
            "id": $id,
            "role": $role,
            "ip": $ip,
            "port": $port,
            "prof": $prof,
            "peers": $peers,
            "retainLogs": $retainLogs,
            "logLevel": $logLevel,
            "logDir": $logDir,
            "walDir": $walDir,
            "warnLogDir": $warnLogDir,
            "storeDir": $storeDir
          }' > /cfs/conf/master.json

  start.sh: |
    #!/bin/sh

    mkdir -p /cfs/log /cfs/data/wal /cfs/data/store /cfs/bin /cfs/conf
    touch /cfs/conf/master.json

    echo "generate master.json"
    /bin/bash /cfs/script/master-json.sh


    echo "start master"
    /cfs/bin/cfs-server -c /cfs/conf/master.json
