apiVersion: v1
kind: Service
metadata:
  name: {{ include "chubaofs-helm.master.fullname" . }}
  labels:
    app: {{ include "chubaofs-helm.name" . }}
    chart: {{ include "chubaofs-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
{{- range $key, $port := .Values.master.ports }}
    - name: {{ $port.name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
{{- end }}
  selector:
    app: {{ include "chubaofs-helm.name" . }}
    release: {{ .Release.Name }}
    role: master
